#!/usr/bin/env bash
trap '' SIGINT SIGQUIT SIGTERM
# ============================================================================= #
#  ➜ ➜ ➜ INSTALL
# ============================================================================= #
if [ -z "$DOTFILES" ]; then
    DOTFILES="$HOME/.dotfiles"
fi
if [ -z "$TERM" ]; then
    TERM='xterm-256color'
fi
INSTALL() {
    "${DOTFILES}/bin/dosync" "--dosync" || exit 1
    exit 0
}
while true; do
    INSTALL "${@}"
done
unset INSTALL
