#!/usr/bin/env bash
trap '' SIGINT SIGQUIT SIGTERM
# ============================================================================= #
#  ➜ ➜ ➜ INSTALL
# ============================================================================= #
# VARIABLES
# ============================================================================= #
XDG_CONFIG_HOME="${HOME}/.config"
XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
# ============================================================================= #
CHECK_LISTS() {
[ ! -d "$XDG_CACHE_HOME"  ] && mkdir -p "$XDG_CACHE_HOME"
[ ! -d "$XDG_CONFIG_HOME" ] && mkdir -p "$XDG_CONFIG_HOME"
[ -z "$DOTFILES" ] && DOTFILES="$HOME/.dotfiles"
[ -z "$TERM" ] && TERM='xterm-256color'
[[ "$(command -v curl)" ]] || echo "Curl - missing" && sleep 2
[[ "$(command -v python)" ]] || echo "Python - missing" && sleep 2
}

INSTALL() {
CHECK_LISTS 
    "${DOTFILES}/bin/dosync" "--dosync" || exit 1
    exit 0
}
while true; do
    INSTALL "${@}"
done
unset INSTALL
