# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
#
# Description: This file is sourced on all invocations of the shell.
# It is the 1st file zsh reads; it's read for every shell, even if started with
# -f (setopt NO_RCS), all other initialization files are skipped.
#
# This file should contain commands to set the command search path, plus other
# important environment variables. This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Loading order: zshenv, zprofile, zshrc, zlogin.

typeset -ghA DOTFILES

DOTFILES[CONFIG]=${HOME}/.dotfiles/.config

source ${DOTFILES[CONFIG]}/go.env

prepend_path() {
  typeset -gxU path PATH
  PATH="${(j/:/)path}"
  path=( "${(@s/:/)PATH}" )
  for add in "$@"; do
    if [[ -d $add ]]; then
      path=( "${add}" "${path[@]}" )
    fi
  done
  path=( "${(@u)path}" ) # remove duplicates
  unset -v add
}

prepend_path "${HOME}/.local/bin"
prepend_path "${HOME}/.yarn/bin"
prepend_path "${HOME}/.local/share/pnpm/bin"
