# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
#
# Description: This file is sourced on all invocations of the shell.
# It is the 1st file zsh reads; it's read for every shell, even if started with
# -f (setopt NO_RCS), all other initialization files are skipped.
#
# This file should contain commands to set the command search path, plus other
# important environment variables. This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Loading order: zshenv, zprofile, zshrc, zlogin.

typeset -ghA DOTFILES

DOTFILES[CONFIG]=${HOME}/.dotfiles/.config

source ${DOTFILES[CONFIG]}/go.sh
source ${DOTFILES[CONFIG]}/pnpm.sh

typeset -gx GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

typeset -gx FLYCTL_INSTALL="${HOME}/.local/share/fly"
typeset -gx PATH="$FLYCTL_INSTALL/bin:$PATH"

if (( $+commands[yarn] )); then
  YARN_PATH="$(yarn global bin)"
else
  YARN_PATH="${HOME}/.local/share/yarn/bin"
fi

typeset -a add_path create_path dir_path

create_path=(
  "${HOME}/.local/bin"
)

add_path=(
  "$YARN_PATH"
)

for dir_path in "${create_path[@]}"; do
  if [[ ! -d $dir_path ]]; then
    mkdir -p $dir_path 2> /dev/null
  fi
done; unset dir_path

prepend_path() {
  typeset -gxU path PATH
  #PATH="${(j/:/)path}"
  #path=( ${(@s/:/)PATH} )
  for add in "$@"; do
    if [[ -d $add ]]; then
      path=( "${add}" "${(@)path}" )
    else
      path=( "${(@)path:#$add}" )
    fi
  done; unset -v add
  path=( "${(@u)path}" )
}

#typeset -a aa
#aa=(test1 test2 test3)
#aa=("${(@)aa:#test2}")

#if (( ${#aa} > 0 )); then
#	echo $aa
#fi


prepend_path "${create_path[@]}"
prepend_path "${add_path[@]}"

unset -f prepend_path
