rules:
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  key-duplicates: enable
  octal-values:
    forbid-implicit-octal: true
