version: 0.1
required_trunk_version: ">=1.17.0"

lint:
  downloads:
    - name: trunk-toolbox
      downloads:
        - os:
            linux: unknown-linux-gnu
            macos: apple-darwin
          cpu:
            x86_64: x86_64
            arm_64: aarch64
          url: https://github.com/trunk-io/toolbox/releases/download/${version}/trunk-toolbox-${version}-${cpu}-${os}.tar.gz

  definitions:
    - name: trunk-toolbox
      download: trunk-toolbox
      files: [ALL]
      commands:
        - output: sarif
          run: trunk-toolbox --upstream ${upstream-ref}
          success_codes: [0]
          read_output_from: stdout
          disable_upstream: true
          target: .
      environment:
        - name: PATH
          list: ["${linter}"]

  disabled:
    - yamllint
    - checkov
    - trufflehog
    - trivy

  enabled:
    - actionlint@1.6.26
    - git-diff-check
    - markdownlint@0.37.0
    - prettier@3.1.0
    - shellcheck@0.9.0
    - shfmt@3.6.0
    - taplo@0.8.1
    - trunk-toolbox@0.0.1

  exported_configs:
    - configs:
        - .hadolint.yaml
        - .markdownlint.yaml
        - .prettierrc.yaml
        - .shellcheckrc
        - .stylelintrc.yaml
        - svgo.config.js

actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
#    - shell-run
#  definitions:
#    - id: shell-run
#      run: run.sh
#      interactive: true

tools:
  enabled:
    - gh@2.39.1

runtimes:
  enabled:
    - go@1.21.0
    - node@18.12.1
    - python@3.10.8
    - ruby@3.1.4
