#!/usr/bin/env bash
###############################################################################
# .nbrc link to home
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_AUTO_SYNC="${NB_AUTO_SYNC:-1}"                  # Set by `nb` • Fri 29 Jan 08:40:02 GMT 2021
export NB_COLOR_THEME="${NB_COLOR_THEME:-console}"        # Set by `nb` • Fri 29 Jan 08:40:36 GMT 2021
export NB_ENCRYPTION_TOOL="${NB_ENCRYPTION_TOOL:-gpg}"    # Set by `nb` • Tue  2 Feb 06:37:06 GMT 2021
export NB_COLOR_PRIMARY="${NB_COLOR_PRIMARY:-46}"         # Set by `nb` • Tue  2 Feb 19:41:07 GMT 2021
export NB_DEFAULT_EXTENSION="${NB_DEFAULT_EXTENSION:-md}" # Set by `nb` • Tue  2 Feb 19:43:12 GMT 2021
export NB_COLOR_SECONDARY="${NB_COLOR_SECONDARY:-8}"      # Set by `nb` • Tue  2 Feb 19:44:10 GMT 2021
export EDITOR="micro"                                     # Set by `nb` • Tue  2 Feb 19:44:30 GMT 2021
export NB_FOOTER="${NB_FOOTER:-1}"                        # Set by `nb` • Tue  2 Feb 19:45:08 GMT 2021
export NB_HEADER="${NB_HEADER:-1}"                        # Set by `nb` • Tue  2 Feb 19:49:17 GMT 2021
export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-ansi-dark}"    # Set by `nb` • Tue  2 Feb 19:54:53 GMT 2021

export NB_DIR="${NB_DIR:-/home/sall/.nb}" # Set by `nb` • Tue  9 Feb 00:30:09 GMT 2021
