---
name: "⭕ Trunk [check]"
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
      - name: ✨ Trunk Check
        uses: trunk-io/trunk-action@d5eb5cd93d004599ec9f44694c5bae5903c55451
